#!/usr/bin/env python3
"""Generate the Hyprland desktop's palette artifacts from palette.py.

Emits, per variant (dark / light):
  hypr/lua/palette.lua        -- tokens consumed by hypr/lua/theme.lua
  hypr/theme/hyprlock-*.conf  -- hyprlang $variables for the lockscreen
  waybar/colors-*.css         -- GTK @define-color tokens for the bar
  rofi/colors-*.rasi          -- rasi color block for the launcher
  swaync/colors-*.css         -- GTK @define-color tokens for notifications
  wlogout/colors-*.css        -- GTK @define-color tokens for the session menu
  hypr/theme/gtk-colors-*.css -- GTK named colors; the standalone stand-in
                                 for what kde-gtk-config writes under KDE
  hypr/theme/kdeglobals-*     -- minimal kdeglobals for machines without a
                                 KDE-managed one (Dolphin & friends)
  hypr/theme/qt6ct-*.conf     -- Kvantum style + icons for Qt apps

The active variant is selected at runtime by hypr/scripts/theme-mode.sh,
which copies colors-<mode>.* over the gitignored colors.* files and lets
hypr/lua/theme.lua re-read the mode state on reload. Nothing here is meant
to be edited by hand — change palette.py and run generate_all.py.
"""
from pathlib import Path

from palette import DARK, LIGHT, G, PLASMA

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]  # dotfiles repo root

# Typography (single place for the Wayland stack; keep in sync with
# home-manager/desktop/fonts.nix, which owns the fontconfig aliases).
FONT_UI = "Inter"
FONT_MONO = "JetBrains Mono"


def _tokens(variant, alt_bg, inactive_border, fg_muted):
    c, s, a = variant["colors"], variant["scheme"], variant["a"]
    return {
        # surfaces
        "bg": c["bg"],
        "bg_alt": alt_bg,
        "field": c["field"],
        "popup": c["popup"],
        # text
        "fg": c["fg"],
        "fg_bright": c["fg_bright"],
        "fg_muted": fg_muted,
        # accents
        "accent": c["accent"],
        "accent_alt": s["selection_alt"],
        "hover": s["accent_hover"],
        "on_accent": s["selection_fg"],
        # semantic
        "negative": s["negative"],
        "neutral": s["neutral"],
        "positive": s["positive"],
        "link": s["link"],
        # window management
        "border_active": c["accent"],
        "border_inactive": inactive_border,
        # opacities (0..1 floats)
        "alpha_panel": PLASMA["panel"][1],
        "alpha_popup": a["menu"],
        "alpha_hairline": a["hairline"],
        "alpha_shadow": a["shadow"],
    }


TOKENS = {
    "dark": _tokens(DARK, alt_bg=G["dark1"],
                    inactive_border=G["dark1"], fg_muted=G["wm_gray"]),
    "light": _tokens(LIGHT, alt_bg=G["light1"],
                     inactive_border=G["light2"], fg_muted=G["gray"]),
}

HEADER = "generated by hyprland_gen.py from palette.py -- do not edit"


def _rgba_hex(hex_color, alpha):
    """'#rrggbb' + 0..1 -> 'rrggbbaa' (no hash)."""
    return f"{hex_color.lstrip('#')}{round(alpha * 255):02x}"


def _rgba_css(hex_color, alpha):
    """'#rrggbb' + 0..1 -> 'rgba(r,g,b,a)' (GTK3 CSS lacks #rrggbbaa)."""
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r},{g},{b},{alpha})"


# ---------------------------------------------------------------- lua
def emit_lua():
    lines = [f"-- {HEADER}", "-- Semantic Gruvbox Dragon tokens, one table per variant.",
             "return {"]
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines.append(f"    {mode} = {{")
        for key, val in t.items():
            if isinstance(val, float):
                lines.append(f"        {key} = {val},")
            else:
                lines.append(f'        {key} = "{val}",')
        lines.append("    },")
    lines.append("}")
    out = ROOT / "hypr" / "lua" / "palette.lua"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- css
def emit_css(subdir, filename_stem):
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines = [f"/* {HEADER} */"]
        for key, val in t.items():
            if isinstance(val, str):
                lines.append(f"@define-color {key} {val};")
        # pre-multiplied acrylic surfaces
        lines.append(f"@define-color bg_panel {_rgba_css(t['bg'], t['alpha_panel'])};")
        lines.append(f"@define-color bg_popup {_rgba_css(t['popup'], t['alpha_popup'])};")
        lines.append(f"@define-color hairline {_rgba_css(t['fg'], t['alpha_hairline'])};")
        out = ROOT / subdir / f"{filename_stem}-{mode}.css"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- rasi
def emit_rasi():
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        body = [f"/* {HEADER} */", "* {"]
        for key, val in t.items():
            if isinstance(val, str):
                # rasi identifiers use dashes, not underscores
                body.append(f"    {key.replace('_', '-')}: {val};")
        body.append(f"    bg-popup: #{_rgba_hex(t['popup'], t['alpha_popup'])};")
        body.append(f"    hairline: #{_rgba_hex(t['fg'], t['alpha_hairline'])};")
        body.append("}")
        out = ROOT / "rofi" / f"colors-{mode}.rasi"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(body) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- hyprlock
def emit_hyprlock():
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines = [f"# {HEADER}"]
        for key, val in t.items():
            if isinstance(val, str):
                lines.append(f"${key} = rgb({val.lstrip('#')})")
        lines.append(f"$bg_scrim = rgba({_rgba_hex(t['bg'], 0.6)})")
        out = ROOT / "hypr" / "theme" / f"hyprlock-{mode}.conf"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ------------------------------------------------------- gtk named colors
def _css_color(value):
    """hex or hex+aa -> css color (GTK3 rejects 8-digit hex)."""
    h = value.lstrip("#")
    if len(h) == 8:
        r, g, b, a = (int(h[i:i + 2], 16) for i in (0, 2, 4, 6))
        return f"rgba({r},{g},{b},{round(a / 255, 3)})"
    return f"#{h}"


def emit_gtk_colors():
    """The GTK named-color sheet kde-gtk-config would write under KDE.

    Breeze's GTK css references these names, so redefining them in the
    user's gtk config dir recolors the whole widget set per mode."""
    for mode, variant in (("dark", DARK), ("light", LIGHT)):
        q, s, t = variant["qt"], variant["scheme"], TOKENS[mode]
        borders = t["border_inactive"]
        colors = {
            "theme_fg_color": q["window.text.color"],
            "theme_text_color": q["text.color"],
            "theme_bg_color": q["window.color"],
            "theme_base_color": q["base.color"],
            "content_view_bg": q["base.color"],
            "theme_selected_bg_color": q["highlight.color"],
            "theme_selected_fg_color": q["highlight.text.color"],
            "theme_hovering_selected_bg_color": s["accent_hover"],
            "theme_view_hover_decoration_color": s["accent_hover"],
            "theme_view_active_decoration_color": t["accent"],
            "theme_button_background_normal": q["button.color"],
            "theme_button_foreground_normal": q["button.text.color"],
            "theme_button_foreground_active": t["fg_bright"],
            "theme_button_decoration_hover": s["accent_hover"],
            "theme_button_decoration_focus": t["accent"],
            "borders": borders,
            "unfocused_borders": borders,
            "insensitive_borders": borders,
            "theme_unfocused_fg_color": t["fg_muted"],
            "theme_unfocused_text_color": t["fg_muted"],
            "theme_unfocused_bg_color": q["window.color"],
            "theme_unfocused_base_color": q["base.color"],
            "theme_unfocused_selected_bg_color": q["inactive.highlight.color"],
            "theme_unfocused_selected_fg_color": q["text.color"],
            "insensitive_fg_color": q["disabled.text.color"],
            "insensitive_base_fg_color": q["disabled.text.color"],
            "insensitive_bg_color": q["window.color"],
            "insensitive_base_color": q["base.color"],
            "unfocused_insensitive_color": q["disabled.text.color"],
            "placeholder_text_color": t["fg_muted"],
            "link_color": q["link.color"],
            "link_visited_color": q["link.visited.color"],
            "success_color": s["positive"],
            "warning_color": s["neutral"],
            "error_color": s["negative"],
            "tooltip_text": q["tooltip.text.color"],
            "tooltip_background": t["popup"],
            "tooltip_border": borders,
        }
        # Breeze GTK's stylesheet references "_breeze"-suffixed twins of the
        # standard names (plus backdrop/insensitive/titlebar variants), so
        # every color is emitted under both — without the twins the theme
        # keeps its baked-in stock palette.
        breeze = {f"{name}_breeze": val for name, val in colors.items()}
        disabled = q["disabled.text.color"]
        breeze.update({
            "text_view_bg": q["base.color"],
            "print_paper_backdrop_breeze": q["base.color"],
            "insensitive_base_fg_color_breeze": disabled,
            "insensitive_selected_bg_color_breeze": q["inactive.highlight.color"],
            "insensitive_selected_fg_color_breeze": disabled,
            "insensitive_unfocused_bg_color_breeze": q["window.color"],
            "insensitive_unfocused_fg_color_breeze": disabled,
            "insensitive_unfocused_selected_bg_color_breeze": q["inactive.highlight.color"],
            "insensitive_unfocused_selected_fg_color_breeze": disabled,
            "unfocused_insensitive_borders_breeze": borders,
            "theme_unfocused_selected_bg_color_alt_breeze": q["inactive.highlight.color"],
            "theme_unfocused_view_bg_color_breeze": q["base.color"],
            "theme_unfocused_view_text_color_breeze": q["text.color"],
            "theme_titlebar_background_breeze": q["window.color"],
            "theme_titlebar_background_light_breeze": t["bg_alt"],
            "theme_titlebar_background_backdrop_breeze": q["window.color"],
            "theme_titlebar_foreground_breeze": q["window.text.color"],
            "theme_titlebar_foreground_backdrop_breeze": t["fg_muted"],
            "theme_titlebar_foreground_insensitive_breeze": disabled,
            "theme_titlebar_foreground_insensitive_backdrop_breeze": disabled,
        })
        for var in ("backdrop", "insensitive", "backdrop_insensitive"):
            breeze[f"theme_button_background_{var}_breeze"] = q["button.color"]
        for deco, val in (("focus", t["accent"]), ("hover", s["accent_hover"])):
            for var in ("backdrop", "insensitive", "backdrop_insensitive"):
                breeze[f"theme_button_decoration_{deco}_{var}_breeze"] = val
        breeze["theme_button_foreground_insensitive_breeze"] = disabled
        for var in ("backdrop", "backdrop_insensitive"):
            breeze[f"theme_button_foreground_{var}_breeze"] = q["button.text.color"]
        for var in ("active_backdrop", "active_insensitive",
                    "active_backdrop_insensitive"):
            breeze[f"theme_button_foreground_{var}_breeze"] = t["fg_bright"]
        for sem, val in (("error", s["negative"]), ("success", s["positive"]),
                         ("warning", s["neutral"])):
            for var in ("backdrop", "insensitive", "insensitive_backdrop"):
                breeze[f"{sem}_color_{var}_breeze"] = val

        lines = [f"/* {HEADER} */"]
        lines += [f"@define-color {name} {_css_color(val)};"
                  for name, val in {**colors, **breeze}.items()]
        out = ROOT / "hypr" / "theme" / f"gtk-colors-{mode}.css"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ------------------------------------------------------------- kdeglobals
# Used only on machines whose kdeglobals is not already KDE/home-manager
# managed (theme-mode.sh prefers kwriteconfig6 edits when a file exists).
KDE_FONTS = {
    "font": "Inter,10.5,-1,5,400,0,0,0,0,0,0,0,0,0,0,1",
    "menuFont": "Inter,10.5,-1,5,400,0,0,0,0,0,0,0,0,0,0,1",
    "toolBarFont": "Inter,10.5,-1,5,400,0,0,0,0,0,0,0,0,0,0,1",
    "smallestReadableFont": "Inter,8,-1,5,400,0,0,0,0,0,0,0,0,0,0,1",
    "fixed": "JetBrains Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1",
}


def emit_kdeglobals():
    for mode, scheme, icons, widget in (
            ("dark", "GruvboxDragon", "Gruvbox-Plus-Dark", "kvantum-dark"),
            ("light", "GruvboxDragonLight", "Gruvbox-Plus-Light", "kvantum")):
        colors_src = (HERE.parents[1] / "color-schemes" / f"{scheme}.colors")
        lines = [f"# {HEADER}",
                 "[General]", f"ColorScheme={scheme}",
                 # ghostty is the terminal everywhere (matches the KDE
                 # session's TerminalApplication)
                 "TerminalApplication=ghostty",
                 "TerminalService=com.mitchellh.ghostty.desktop"]
        lines += [f"{k}={v}" for k, v in KDE_FONTS.items()]
        lines += ["XftAntialias=true", "XftHintStyle=hintslight",
                  "XftSubPixel=none", "",
                  "[Icons]", f"Theme={icons}", "",
                  "[KDE]", f"widgetStyle={widget}",
                  "AnimationDurationFactor=0.25", ""]
        # inline the color groups so apps work even before the scheme file
        # is discoverable under ~/.local/share/color-schemes
        lines.append(colors_src.read_text(encoding="utf-8"))
        out = ROOT / "hypr" / "theme" / f"kdeglobals-{mode}"
        out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


def emit_qt6ct():
    for mode, icons, style in (("dark", "Gruvbox-Plus-Dark", "kvantum-dark"),
                               ("light", "Gruvbox-Plus-Light", "kvantum")):
        body = (f"# {HEADER}\n"
                "[Appearance]\n"
                f"style={style}\n"
                f"icon_theme={icons}\n"
                "custom_palette=false\n"
                "standard_dialogs=default\n")
        out = ROOT / "hypr" / "theme" / f"qt6ct-{mode}.conf"
        out.write_text(body, encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


if __name__ == "__main__":
    emit_lua()
    emit_css("waybar", "colors")
    emit_css("swaync", "colors")
    emit_css("wlogout", "colors")
    emit_rasi()
    emit_hyprlock()
    emit_gtk_colors()
    emit_kdeglobals()
    emit_qt6ct()
