#!/usr/bin/env python3
"""Generate the Hyprland desktop's palette artifacts from palette.py.

Emits, per variant (dark / light):
  hypr/lua/palette.lua        -- tokens consumed by hypr/lua/theme.lua
  hypr/theme/hyprlock-*.conf  -- hyprlang $variables for the lockscreen
  waybar/colors-*.css         -- GTK @define-color tokens for the bar
  rofi/colors-*.rasi          -- rasi color block for the launcher
  swaync/colors-*.css         -- GTK @define-color tokens for notifications
  wlogout/colors-*.css        -- GTK @define-color tokens for the session menu

The active variant is selected at runtime by hypr/scripts/theme-mode.sh,
which copies colors-<mode>.* over the gitignored colors.* files and lets
hypr/lua/theme.lua re-read the mode state on reload. Nothing here is meant
to be edited by hand — change palette.py and run generate_all.py.
"""
from pathlib import Path

from palette import DARK, LIGHT, G, PLASMA

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]  # dotfiles repo root

# Typography (single place for the Wayland stack; keep in sync with
# home-manager/desktop/fonts.nix, which owns the fontconfig aliases).
FONT_UI = "Inter"
FONT_MONO = "JetBrains Mono"


def _tokens(variant, alt_bg, inactive_border, fg_muted):
    c, s, a = variant["colors"], variant["scheme"], variant["a"]
    return {
        # surfaces
        "bg": c["bg"],
        "bg_alt": alt_bg,
        "field": c["field"],
        "popup": c["popup"],
        # text
        "fg": c["fg"],
        "fg_bright": c["fg_bright"],
        "fg_muted": fg_muted,
        # accents
        "accent": c["accent"],
        "accent_alt": s["selection_alt"],
        "hover": s["accent_hover"],
        "on_accent": s["selection_fg"],
        # semantic
        "negative": s["negative"],
        "neutral": s["neutral"],
        "positive": s["positive"],
        "link": s["link"],
        # window management
        "border_active": c["accent"],
        "border_inactive": inactive_border,
        # opacities (0..1 floats)
        "alpha_panel": PLASMA["panel"][1],
        "alpha_popup": a["menu"],
        "alpha_hairline": a["hairline"],
        "alpha_shadow": a["shadow"],
    }


TOKENS = {
    "dark": _tokens(DARK, alt_bg=G["dark1"],
                    inactive_border=G["dark1"], fg_muted=G["wm_gray"]),
    "light": _tokens(LIGHT, alt_bg=G["light1"],
                     inactive_border=G["light2"], fg_muted=G["gray"]),
}

HEADER = "generated by hyprland_gen.py from palette.py -- do not edit"


def _rgba_hex(hex_color, alpha):
    """'#rrggbb' + 0..1 -> 'rrggbbaa' (no hash)."""
    return f"{hex_color.lstrip('#')}{round(alpha * 255):02x}"


# ---------------------------------------------------------------- lua
def emit_lua():
    lines = [f"-- {HEADER}", "-- Semantic Gruvbox Dragon tokens, one table per variant.",
             "return {"]
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines.append(f"    {mode} = {{")
        for key, val in t.items():
            if isinstance(val, float):
                lines.append(f"        {key} = {val},")
            else:
                lines.append(f'        {key} = "{val}",')
        lines.append("    },")
    lines.append("}")
    out = ROOT / "hypr" / "lua" / "palette.lua"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- css
def emit_css(subdir, filename_stem):
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines = [f"/* {HEADER} */"]
        for key, val in t.items():
            if isinstance(val, str):
                lines.append(f"@define-color {key} {val};")
        # pre-multiplied acrylic surfaces (GTK css lacks a hex+alpha helper)
        lines.append(f"@define-color bg_panel #{_rgba_hex(t['bg'], t['alpha_panel'])};")
        lines.append(f"@define-color bg_popup #{_rgba_hex(t['popup'], t['alpha_popup'])};")
        lines.append(f"@define-color hairline #{_rgba_hex(t['fg'], t['alpha_hairline'])};")
        out = ROOT / subdir / f"{filename_stem}-{mode}.css"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- rasi
def emit_rasi():
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        body = [f"/* {HEADER} */", "* {"]
        for key, val in t.items():
            if isinstance(val, str):
                # rasi identifiers use dashes, not underscores
                body.append(f"    {key.replace('_', '-')}: {val};")
        body.append(f"    bg-popup: #{_rgba_hex(t['popup'], t['alpha_popup'])};")
        body.append(f"    hairline: #{_rgba_hex(t['fg'], t['alpha_hairline'])};")
        body.append("}")
        out = ROOT / "rofi" / f"colors-{mode}.rasi"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(body) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- hyprlock
def emit_hyprlock():
    for mode in ("dark", "light"):
        t = TOKENS[mode]
        lines = [f"# {HEADER}"]
        for key, val in t.items():
            if isinstance(val, str):
                lines.append(f"${key} = rgb({val.lstrip('#')})")
        lines.append(f"$bg_scrim = rgba({_rgba_hex(t['bg'], 0.6)})")
        out = ROOT / "hypr" / "theme" / f"hyprlock-{mode}.conf"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        print(f"  {out.relative_to(ROOT)}")


if __name__ == "__main__":
    emit_lua()
    emit_css("waybar", "colors")
    emit_css("swaync", "colors")
    emit_css("wlogout", "colors")
    emit_rasi()
    emit_hyprlock()
